// Public media paths are kept here so reorganizing assets never requires JSX edits.
export const media = {
  logoOnDark: "/images/brand/robofounders-logo-new.png",
  logoOnLight: "/images/brand/robofounders-logo-new.png",
  logoSquare: "/images/brand/robofounders-mark-square.webp",
  logoGalaxy: "/images/brand/robofounders-galaxy-mark.webp",
  contactAddressLight: "/images/brand/contact-address-light.png",
  contactAddressDark: "/images/brand/contact-address-dark.png",
  founder: "/images/team/mariel.webp",
  rofi: "/images/home/rofi-3d.png",
  homeVideo: "/videos/home/physical-ai-concept.mp4?v=20261005",
  conceptFilm: "/videos/home/robofounders-one-minute.mp4",
  conceptFilmPoster: "/images/home/robofounders-one-minute-poster.jpg",
  home: {
    hero: "/images/home/physical-ai-video-poster.webp",
    heroDangerousWork: "/images/home/dangerous-manufacturing.webp",
    about: "/images/home/about-factory-team.webp",
    regions: "/images/home/global-ecosystem.webp",
    why: "/images/home/why-robofounders.webp",
    factory: "/images/home/factory-deployment.webp",
    factoryVideo: "/videos/home/factory-deployment.mp4",
    factoryVideoPoster: "/images/home/factory-deployment-video-poster.webp",
    startups: "/images/home/startups-jungle.jpg",
    contact: "/images/news/startup-world-cup-tokyo/team-booth-client.webp",
  },
  team: {
    takeshi: "/images/team/takeshi.webp",
    hiromichi: "/images/team/hiromichi.png",
    eiichiro: "/images/team/eiichiro.webp",
    yasumitsu: "/images/team/yasumitsu.webp",
    hiro: "/images/team/hiro.webp",
    hao: "/images/team/hao.webp",
    mai: "/images/team/mai.webp",
    celine: "/images/team/celine.webp",
    thao: "/images/team/thao.webp",
  },
  newsBanner: "/images/events/news-banner.jpg",
  newsEvent: "/images/events/news-event-new.jpg",
  ivs2026News: "/images/news/ivs-2026/founder-at-ivs.webp",
  beyondPocPortrait: "/images/news/diffusion-borneo-beyond-poc/hero.webp",
  beyondPocStage: "/images/news/diffusion-borneo-beyond-poc/client-stage.jpeg",
  aseanSummit: "/images/works/asean-summit.jpeg",
  aseanMou: "/images/works/asean-mou.jpg",
  nikkeiCoverage: "/images/news/nikkei-genai-sum/print-coverage.jpg",
  kabilanPortrait: "/images/news/kabilan-kb/portrait.jpg",
  diffusionBorneo: "/images/events/diffusion-borneo.jpeg",
  xHubSingapore: "/images/news/x-hub-singapore/hero.jpg",
  aiMalaysiaTakeover: "/images/news/ai-malaysia-takeover-2026/hero.png",
  japanCorporation: "/images/news/japan-corporation/client-photo.jpg",
  startupWorldCupTokyo: "/images/news/startup-world-cup-tokyo/team-booth-client.webp",
  robotHandNew: "/images/products/robot-hand-new.jpg",
  bostonAiWeek: "/images/events/boston-ai-week.jpeg",
  startupWorldCup: "/images/news/startup-world-cup-tokyo/founder-rofi-client.webp",
  beamstartHero: "/images/news/beamstart/founder-professor-sankai.webp",
  ivsExhibit: "/images/news/ivs-2026/founder-at-ivs.webp",
  events: [
    "/images/news/ivs-2026/founder-at-ivs.webp",
    "ivs-poster.jpeg",
    "team-banner",
    "booth-laptop",
    "banner-booth",
    "stickers",
    "ivs-poster",
    "startups-jungle",
    "boston-ecosystem",
  ].map((name) => {
    if (name.startsWith("/")) return name;
    return name.includes(".")
      ? `/images/events/${name}`
      : `/images/events/${name}.jpeg`;
  }),
  galleryItems: [
    { type: "image", src: "/images/news/ivs-2026/founder-at-ivs.webp", size: [1600, 1316] },
    { type: "video", src: "/videos/events/abis-summit.mp4", poster: "/images/events/video-posters/abis-summit.webp" },
    { type: "image", src: "/images/events/team-banner.jpeg", size: [960, 1280] },
    { type: "video", src: "/videos/events/ai-malaysia-takeover.mp4", poster: "/images/events/video-posters/ai-malaysia-takeover.webp" },
    { type: "video", src: "/videos/events/jungle-forge-awards.mp4", poster: "/images/events/video-posters/jungle-forge-awards.webp" },
    { type: "image", src: "/images/events/stickers.jpeg", size: [1280, 1707] },
    { type: "video", src: "/videos/events/jetro-boston-demo-day.mp4", poster: "/images/events/video-posters/jetro-boston-demo-day.webp" },
    { type: "video", src: "/videos/events/japanese-lessons.mp4", poster: "/images/events/video-posters/japanese-lessons.webp" },
    { type: "image", src: "/images/events/boston-ecosystem.jpeg", size: [1024, 768] },
    ...["event-demo", "event-clip2", "event-clip1"].map((name, index) => ({
      type: "video",
      src: `/videos/events/${name}.mp4`,
      poster: `/images/events/video-posters/${name}.webp`,
    })),
  ],
  products: {
    "roller-screw": {
      hero: "/images/products/roller-screw/assembly",
      gallery: ["/images/products/roller-screw/assembly"],
      video: "/videos/products/roller-screw/demonstration.mp4",
    },
    "robotic-hand": {
      hero: "/images/products/robotic-hand/food-handling",
      gallery: [
        "/images/products/robotic-hand/applications",
        "/images/products/robotic-hand/precision-handling",
      ],
    },
  },
};
export const productIds = ["roller-screw", "robotic-hand"];
// Actual exported dimensions; portrait variants are constrained by height.
export const productImageSizes = {
  assembly: { small: 640, width: 962, height: 954 },
  "close-up": { small: 640, width: 1600, height: 1200 },
  "food-handling": { small: 640, width: 1600, height: 901 },
  applications: { small: 640, width: 1600, height: 900 },
  "precision-handling": { small: 640, width: 1600, height: 606 },
};
export const contacts = {
  endpoint: "https://formsubmit.co/ajax/r@robofounders.ai",
  cc: "tak@robofounders.net,mai.robofounders@gmail.com,marieasami7@gmail.com",
  linkedin: "https://www.linkedin.com/company/robofounders/",
  linkedinJapan: "https://www.linkedin.com/company/robofoundersjp/",
  linkedinMalaysia: "https://www.linkedin.com/company/robofoundersmy/",
  founderLinkedin: "https://www.linkedin.com/in/marie-asami/",
  facebook: "https://www.facebook.com/robofounders",
  x: "https://x.com/robofounders",
  instagram: "https://www.instagram.com/robofounders",
  youtube: "https://www.youtube.com/@RoboFounders",
};
